// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/scrape-hub/configs"
	"github.com/blackhorseya/scrape-hub/internal/app/providers"
	"github.com/blackhorseya/scrape-hub/internal/delivery/http"
)

// Injectors from wire.go:

// InitializeApp 初始化應用程式
func InitializeApp(cfg *configs.Config) (http.Server, error) {
	awsClients, err := providers.ProvideAWSClients()
	if err != nil {
		return nil, err
	}
	taskRepository := providers.ProvideTaskRepository(awsClients)
	taskQuery := providers.ProvideTaskQuery(taskRepository)
	server, err := providers.ProvideHTTPServer(cfg, taskQuery)
	if err != nil {
		return nil, err
	}
	return server, nil
}
